# Configuration file for DistantSpawns

bed:
  # Maximum distance from world spawn (in overworld blocks, not nether
  # blocks) where people can set their spawn using beds.
  max-distance: 3200.0

  # Message shown when someone tries to use a bed too far from spawn.
  # Valid placeholders:
  # - %distance% = The max-distance option
  too-far-msg: "&cYour spawn was not set because you are more than %distance% blocks away from world spawn. Use a respawn anchor."

anchor:
  # Message shown when someone tries to refill an anchor past its
  # maximum capacity far from spawn.
  # Valid placeholders:
  # - %capacity% = The remaining capacity of the anchor
  # - %unit% = The plural or singular (depending on %capacity%) word for charge unit, as configured below
  full-msg: "&cThis anchor can only hold %capacity% %unit%."

  # Message shown when someone's respawn anchor is broken after reaching a
  # capacity of zero.
  depleted-msg: "&cYour respawn anchor can no longer hold any charges and has been destroyed."

  # Lore string that shows the remaining capacity of a respawn anchor.
  # Valid placeholders:
  # - %capacity% = The remaining capacity of the anchor
  # - %unit% = The plural or singular (depending on %capacity%) word for charge unit, as configured below
  lore: "&7Capacity: &6%capacity% %unit%"

  # Used in other messages to signify a unit of charge for a respawn anchor.
  # Singular is used when the capacity is 1, and plural is used otherwise.
  singular-charge: "charge"
  plural-charges: "charges"

cmd-msgs:
  # Messages shown when reloading the configuration.
  reloaded: "&7[&5DistantSpawns&7] &fReloaded configuration."
  reloaded-fail: "&7[&5DistantSpawns&7] &cFailed to reload configuration."
